export interface HourlyWeather {
  time: string[]
  temperature_2m: number[]
  relativehumidity_2m: number[]
  dewpoint_2m: number[]
  apparent_temperature: number[]
  precipitation: number[]
  rain: number[]
  showers: number[]
  weathercode: number[]
  preassure_msl: number[]
  surface_preasure: number[]
  cloudcover: number[]
  visibility: number[]
  windspeed_10m: number[]
  winddirection_10m: number[]
  windgusts_10m: number[]
  soil_temperature_0cm: number[]
}
