export interface HourlyWeather {
  time: string[]
  temperature: number[]
  relativehumidity: number[]
  dewpoint: number[]
  apparent_temperature: number[]
  precipitation: number[]
  rain: number[]
  showers: number[]
  weathercode: number[]
  preassure: number[]
  surface_preasure: number[]
  cloudcover: number[]
  visibility: number[]
  windspeed: number[]
  winddirection: number[]
  windgusts: number[]
  soil_temperature: number[]
}
