export interface DailyWeather {
  time: string[]
  weathercode: number[]
  temperature_max: number[]
  temperature_min: number[]
  apparent_temperature_max: number[]
  apparent_temperature_min: number[]
  sunrise: string[]
  sunset: string[]
  precipitation: number[]
  rain: number[]
  showers: number[]
  snowfall: number[]
  precipitation_hours: number[]
  windspeed_max: number[]
  windgusts_max: number[]
  winddirection_dominant: number[]
  shortwave_radiation: number[]
}
